using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class VR_XInput : MonoBehaviour
{
    public InputActionReference Xbtn;
    public Transform _axePos;
    public Transform _torchPos;

    public GameObject _axe;
    public GameObject _torch;

    private bool isHoldingX = false; // X ลฐธฆ ฒฺ ดฉธฃฐํ ภึดยม๖ ฟฉบฮธฆ ณชลธณปดย วรทกฑื
    private float holdDuration = 1f; // X ลฐธฆ ฒฺ ดฉธฅ ม๖ผำ ฝรฐฃ
    private float currentHoldTime = 0f; // ว๖ภ็ X ลฐธฆ ฒฺ ดฉธฅ ฝรฐฃ

    private void OnEnable()
    {
        // X ลฐ ภิทย พืผวฟก ด๋วั ธฎฝบณส ต๎ทฯ
        Xbtn.action.started += OnXButtonPressed;
        Xbtn.action.canceled += OnXButtonReleased;
    }

    private void OnDisable()
    {
        // X ลฐ ภิทย พืผวฟก ด๋วั ธฎฝบณส วุมฆ
        Xbtn.action.started -= OnXButtonPressed;
        Xbtn.action.canceled -= OnXButtonReleased;
    }

    private void Update()
    {
        // X ลฐธฆ ฒฺ ดฉธฃฐํ ภึดย ตฟพศ ฟขฝบฟอ ลไฤกธฆ equipmentPosition ภงฤกทฮ ภฬตฟ
        if (isHoldingX)
        {
            currentHoldTime += Time.deltaTime; // ว๖ภ็ ฒฺ ดฉธฅ ฝรฐฃ ร๘มค
            if (currentHoldTime >= holdDuration) // ม๖มคตศ ฝรฐฃ ภฬป๓ ฒฺ ดฉธฅ ฐๆฟ์
            {
                // ฟขฝบฟอ ลไฤกธฆ equipmentPosition ภงฤกทฮ ภฬตฟ
                _axe.transform.position = _axePos.position;
                _torch.transform.position = _torchPos.position;
            }
        }
    }

    private void OnXButtonPressed(InputAction.CallbackContext context)
    {
        // X ลฐฐก ดญธฐ ฐๆฟ์
        isHoldingX = true;
        currentHoldTime = 0f;
    }

    private void OnXButtonReleased(InputAction.CallbackContext context)
    {
        // X ลฐฐก ถผม๘ ฐๆฟ์
        isHoldingX = false;
        currentHoldTime = 0f;
    }

}
